const en = {
  // Dashboard
  'dash.title': 'Overview',
  'dash.received': 'Received',
  'dash.revenue': 'Revenue',
  'dash.cost': 'Cost',
  'dash.profit': 'Profit',
  'dash.customerDues': 'Customer dues',
  'dash.supplierPayables': 'Supplier payables',
  'dash.range.7d': '7 days',
  'dash.range.1m': '1 month',
  'dash.range.3m': '3 months',
  'dash.range.6m': '6 months',
  'dash.range.9m': '9 months',
  'dash.range.1y': '1 year',
  'dash.range.lifetime': 'Lifetime',
  'dash.revenueTrend': 'Revenue trend',
  'dash.recentActivity': 'Recent activity',
  'dash.noActivity': 'No recent activity',
  'dash.noData': 'No data for this range',
  'dash.loadError': "Couldn't load the dashboard.",
  'dash.retry': 'Retry',

  // Bills
  'bills.title': 'Bills',
  'bills.search': 'Search invoices…',
  'bills.all': 'All',
  'bills.paid': 'Paid',
  'bills.pending': 'Pending',
  'bills.summaryTotal': 'Total',
  'bills.summaryPaid': 'Paid',
  'bills.summaryPending': 'Pending',
  'bills.invoices': 'Invoices',
  'bills.noInvoices': 'No invoices yet',
  'bills.noInvoicesHint': 'Create your first invoice to see it here.',
  'bills.purchases': 'Purchase documents',
  'bills.purchaseOrders': 'Purchase orders',
  'bills.deliveredPurchases': 'Delivered purchases',
  'bills.noPurchases': 'No purchase documents yet',
  'bills.delivered': 'Delivered',
  'bills.notDelivered': 'Not delivered',
  'bills.itemsSuffix': 'items',
  'bills.loadError': "Couldn't load bills.",

  // Invoice detail
  'inv.back': 'Back',
  'inv.shareWhatsApp': 'Share on WhatsApp',
  'inv.shareOther': 'Share image to another app',
  'inv.createAnother': 'Create another invoice',
  'inv.loadError': "Couldn't load the invoice.",
  'inv.retry': 'Retry',
  'inv.billTo': 'Bill to',
  'inv.invoiceNo': 'Invoice no.',
  'inv.date': 'Date',
  'inv.paymentMethod': 'Payment method',
  'inv.status': 'Status',
  'inv.notes': 'Notes',
  'inv.subtotal': 'Subtotal',
  'inv.discount': 'Discount',
  'inv.total': 'Total',
  'inv.thankYou': 'Thank you for your business!',
  'inv.paid': 'Paid',
  'inv.pending': 'Pending',

  // Create invoice
  'create.title': 'Create invoice',
  'create.customer': 'Customer',
  'create.selectCustomer': 'Select customer',
  'create.date': 'Date',
  'create.products': 'Products',
  'create.searchProducts': 'Search products…',
  'create.stock': 'in stock',
  'create.add': 'Add',
  'create.lineItems': 'Items',
  'create.noItems': 'No items yet — add products above.',
  'create.qty': 'Qty',
  'create.price': 'Price',
  'create.remove': 'Remove',
  'create.discount': 'Discount',
  'create.paymentMethod': 'Payment method',
  'create.dueStatus': 'Status',
  'create.paid': 'Paid',
  'create.pending': 'Pending',
  'create.accent': 'Accent colour',
  'create.logo': 'Shop logo',
  'create.uploadLogo': 'Upload logo',
  'create.changeLogo': 'Change logo',
  'create.notes': 'Notes',
  'create.notesPh': 'Optional note…',
  'create.preview': 'Live preview',
  'create.submit': 'Create invoice',
  'create.creating': 'Creating…',
  'create.needCustomer': 'Please select a customer.',
  'create.needItems': 'Add at least one item.',
  'create.stockBlocked': 'Only {n} in stock.',
  'create.createError': "Couldn't create the invoice.",
  'create.noCustomers': 'No customers yet — add one from Contacts.',
  'create.noProducts': 'No products yet — add some from Products.',

  // Payment methods
  'pay.cash': 'Cash',
  'pay.bank': 'Bank transfer',
  'pay.card': 'Card',
  'pay.mobile': 'Mobile wallet',

  // Share flow
  'share.preparing': 'Preparing…',
  'share.downloaded': 'Downloaded',
  'share.downloadHint': 'Opening WhatsApp — attach the downloaded image to send it.',
  'share.error': "Couldn't prepare the image. Try again.",
  'share.retry': 'Retry',
  'share.close': 'Close',
  'share.shared': 'Shared',
} as const;

export default en;
