// Feature B (catalog, contacts, profile, admin) — Urdu strings.
const ur: Record<string, string> = {
  // Contacts list
  'contacts.title': 'رابطے',
  'contacts.customers': 'گاہک',
  'contacts.suppliers': 'سپلائرز',
  'contacts.searchCustomers': 'گاہک کا نام یا فون تلاش کریں…',
  'contacts.searchSuppliers': 'سپلائر کا نام یا فون تلاش کریں…',
  'contacts.addCustomer': 'نیا گاہک',
  'contacts.addSupplier': 'نیا سپلائر',
  'contacts.name': 'نام',
  'contacts.phone': 'فون نمبر',
  'contacts.address': 'پتہ',
  'contacts.addressOptional': 'پتہ (اختیاری)',
  'contacts.save': 'محفوظ کریں',
  'contacts.saving': 'محفوظ ہو رہا ہے…',
  'contacts.cancel': 'منسوخ کریں',
  'contacts.totalBilled': 'کل بلنگ',
  'contacts.totalPayable': 'کل واجب الادا',
  'contacts.invoices': 'بل',
  'contacts.purchases': 'خریداریاں',
  'contacts.noCustomers': 'ابھی کوئی گاہک نہیں',
  'contacts.noSuppliers': 'ابھی کوئی سپلائر نہیں',
  'contacts.addFirst': 'شروع کرنے کے لیے پہلا {type} شامل کریں۔',
  'contacts.nameRequired': 'نام ضروری ہے',
  'contacts.phoneInvalid': 'درست فون نمبر لکھیں جیسے 0300-1234567',
  'contacts.phoneHint': 'فارمیٹ: 0300-0000000',
  'contacts.errorLoad': 'رابطے لوڈ نہیں ہو سکے',

  // Contact detail
  'contactDetail.back': 'واپس',
  'contactDetail.customer': 'گاہک',
  'contactDetail.supplier': 'سپلائر',
  'contactDetail.totalBilled': 'کل بلنگ',
  'contactDetail.totalPayable': 'کل واجب الادا',
  'contactDetail.invoices': 'بل',
  'contactDetail.purchases': 'خریداریاں',
  'contactDetail.paid': 'وصول شدہ',
  'contactDetail.pending': 'بقایا',
  'contactDetail.lastTransaction': 'آخری لین دین',
  'contactDetail.never': 'کبھی نہیں',
  'contactDetail.history': 'لین دین کی تفصیل',
  'contactDetail.noHistory': 'ابھی کوئی ریکارڈ نہیں',
  'contactDetail.paidBadge': 'ادا شدہ',
  'contactDetail.pendingBadge': 'بقایا',
  'contactDetail.delivered': 'موصول',
  'contactDetail.purchaseOrder': 'پرچیز آرڈر',
  'contactDetail.errorLoad': 'تفصیل لوڈ نہیں ہو سکی',

  // Products
  'products.title': 'پروڈکٹس',
  'products.search': 'پروڈکٹ تلاش کریں…',
  'products.addProduct': 'نیا پروڈکٹ',
  'products.editProduct': 'پروڈکٹ میں ترمیم',
  'products.edit': 'ترمیم',
  'products.name': 'پروڈکٹ کا نام',
  'products.costPrice': 'خرید قیمت',
  'products.sellingPrice': 'فروخت قیمت',
  'products.stock': 'اسٹاک',
  'products.save': 'محفوظ کریں',
  'products.saving': 'محفوظ ہو رہا ہے…',
  'products.cancel': 'منسوخ کریں',
  'products.delete': 'حذف کریں',
  'products.deleteTitle': 'پروڈکٹ حذف کریں؟',
  'products.deleteConfirm': 'کیا آپ واقعی "{name}" حذف کرنا چاہتے ہیں؟ یہ عمل واپس نہیں ہوگا۔',
  'products.confirmDelete': 'جی ہاں، حذف کریں',
  'products.lowStock': 'کم اسٹاک',
  'products.outOfStock': 'اسٹاک ختم',
  'products.inStock': 'اسٹاک میں',
  'products.noProducts': 'ابھی کوئی پروڈکٹ نہیں',
  'products.noProductsHint': 'بل بنانے کے لیے اپنی دکان کی اشیاء یہاں شامل کریں۔',
  'products.nameRequired': 'پروڈکٹ کا نام ضروری ہے',
  'products.invalidPrice': 'درست قیمت لکھیں',
  'products.cost': 'خرید',
  'products.selling': 'فروخت',
  'products.errorLoad': 'پروڈکٹس لوڈ نہیں ہو سکے',

  // New purchase
  'purchase.title': 'نئی خریداری',
  'purchase.supplier': 'سپلائر',
  'purchase.selectSupplier': 'سپلائر منتخب کریں',
  'purchase.type': 'قسم',
  'purchase.purchaseOrder': 'پرچیز آرڈر',
  'purchase.deliveredPurchase': 'موصول خریداری',
  'purchase.poHint': 'پرچیز آرڈر میں اسٹاک شامل نہیں ہوتا جب تک اسے "موصول" نہ کیا جائے۔',
  'purchase.deliveredHint': 'موصول خریداری میں اسٹاک فوراً بڑھ جاتا ہے۔',
  'purchase.items': 'اشیاء',
  'purchase.product': 'پروڈکٹ',
  'purchase.selectProduct': 'پروڈکٹ منتخب کریں',
  'purchase.qty': 'تعداد',
  'purchase.cost': 'فی یونٹ لاگت',
  'purchase.addItem': 'آئٹم شامل کریں',
  'purchase.removeItem': 'ہٹائیں',
  'purchase.notes': 'نوٹس',
  'purchase.notesPlaceholder': 'اضافی تفصیل (اختیاری)',
  'purchase.date': 'تاریخ',
  'purchase.total': 'کل',
  'purchase.create': 'خریداری محفوظ کریں',
  'purchase.creating': 'محفوظ ہو رہا ہے…',
  'purchase.selectSupplierFirst': 'پہلے سپلائر منتخب کریں',
  'purchase.addAtLeastOne': 'کم از کم ایک آئٹم شامل کریں',
  'purchase.invalidItem': 'ہر آئٹم میں پروڈکٹ، تعداد اور لاگت ضروری ہے',
  'purchase.errorLoad': 'ڈیٹا لوڈ نہیں ہو سکا',

  // Profile
  'profile.title': 'پروفائل',
  'profile.shopInfo': 'دکان کی معلومات',
  'profile.shopName': 'دکان کا نام',
  'profile.shopAddress': 'دکان کا پتہ',
  'profile.phone': 'فون نمبر',
  'profile.userName': 'نام',
  'profile.language': 'زبان',
  'profile.english': 'English',
  'profile.urdu': 'اردو',
  'profile.theme': 'تھیم',
  'profile.light': 'لائٹ',
  'profile.dark': 'ڈارک',
  'profile.feedback': 'فیڈبیک بھیجیں',
  'profile.feedbackHint': 'مسئلہ بتائیں یا تجویز دیں',
  'profile.logout': 'لاگ آؤٹ',
  'profile.adminPanel': 'ایڈمن پینل',
  'profile.adminHint': 'رجسٹرڈ اکاؤنٹس اور صارفین کی رائے دیکھیں',

  // Feedback
  'feedback.title': 'فیڈبیک',
  'feedback.category': 'کیٹیگری',
  'feedback.bug': 'مسئلہ',
  'feedback.suggestion': 'تجویز',
  'feedback.other': 'دیگر',
  'feedback.message': 'پیغام',
  'feedback.messagePlaceholder': 'اپنا مسئلہ یا تجویز یہاں لکھیں…',
  'feedback.submit': 'بھیجیں',
  'feedback.submitting': 'بھیجا جا رہا ہے…',
  'feedback.messageRequired': 'براہ کرم پیغام لکھیں',
  'feedback.thankYou': 'شکریہ!',
  'feedback.thankYouHint': 'آپ کی رائے موصول ہو گئی ہے۔ ہم جلد اس پر غور کریں گے۔',
  'feedback.back': 'پروفائل پر واپس جائیں',

  // Admin
  'admin.title': 'ایڈمن پینل',
  'admin.accessDenied': 'رسائی نہیں ہے',
  'admin.accessDeniedHint': 'یہ صفحہ صرف ایڈمن کے لیے ہے۔',
  'admin.accounts': 'رجسٹرڈ اکاؤنٹس',
  'admin.userFeedback': 'صارفین کی رائے',
  'admin.noAccounts': 'ابھی کوئی اکاؤنٹ نہیں',
  'admin.noFeedback': 'ابھی کوئی فیڈبیک نہیں',
  'admin.createdOn': 'شمولیت',
  'admin.errorLoad': 'ڈیٹا لوڈ نہیں ہو سکا',
};

export default ur;
