// Feature B (catalog, contacts, profile, admin) — English strings.
const en: Record<string, string> = {
  // Contacts list
  'contacts.title': 'Contacts',
  'contacts.customers': 'Customers',
  'contacts.suppliers': 'Suppliers',
  'contacts.searchCustomers': 'Search customer name or phone…',
  'contacts.searchSuppliers': 'Search supplier name or phone…',
  'contacts.addCustomer': 'Add customer',
  'contacts.addSupplier': 'Add supplier',
  'contacts.name': 'Name',
  'contacts.phone': 'Phone',
  'contacts.address': 'Address',
  'contacts.addressOptional': 'Address (optional)',
  'contacts.save': 'Save',
  'contacts.saving': 'Saving…',
  'contacts.cancel': 'Cancel',
  'contacts.totalBilled': 'Total billed',
  'contacts.totalPayable': 'Total payable',
  'contacts.invoices': 'invoices',
  'contacts.purchases': 'purchases',
  'contacts.noCustomers': 'No customers yet',
  'contacts.noSuppliers': 'No suppliers yet',
  'contacts.addFirst': 'Add your first {type} to get started.',
  'contacts.nameRequired': 'Name is required',
  'contacts.phoneInvalid': 'Enter a valid phone like 0300-1234567',
  'contacts.phoneHint': 'Format: 0300-0000000',
  'contacts.errorLoad': 'Could not load contacts',

  // Contact detail
  'contactDetail.back': 'Back',
  'contactDetail.customer': 'Customer',
  'contactDetail.supplier': 'Supplier',
  'contactDetail.totalBilled': 'Total billed',
  'contactDetail.totalPayable': 'Total payable',
  'contactDetail.invoices': 'Invoices',
  'contactDetail.purchases': 'Purchases',
  'contactDetail.paid': 'Paid',
  'contactDetail.pending': 'Pending',
  'contactDetail.lastTransaction': 'Last transaction',
  'contactDetail.never': 'Never',
  'contactDetail.history': 'Transaction history',
  'contactDetail.noHistory': 'No transactions yet',
  'contactDetail.paidBadge': 'Paid',
  'contactDetail.pendingBadge': 'Pending',
  'contactDetail.delivered': 'Delivered',
  'contactDetail.purchaseOrder': 'Purchase order',
  'contactDetail.errorLoad': 'Could not load details',

  // Products
  'products.title': 'Products',
  'products.search': 'Search products…',
  'products.addProduct': 'Add product',
  'products.editProduct': 'Edit product',
  'products.edit': 'Edit',
  'products.name': 'Product name',
  'products.costPrice': 'Cost price',
  'products.sellingPrice': 'Selling price',
  'products.stock': 'Stock',
  'products.save': 'Save',
  'products.saving': 'Saving…',
  'products.cancel': 'Cancel',
  'products.delete': 'Delete',
  'products.deleteTitle': 'Delete product?',
  'products.deleteConfirm': 'Are you sure you want to delete "{name}"? This cannot be undone.',
  'products.confirmDelete': 'Yes, delete',
  'products.lowStock': 'Low stock',
  'products.outOfStock': 'Out of stock',
  'products.inStock': 'In stock',
  'products.noProducts': 'No products yet',
  'products.noProductsHint': 'Add your shop items here to use them in invoices.',
  'products.nameRequired': 'Product name is required',
  'products.invalidPrice': 'Enter a valid price',
  'products.cost': 'Cost',
  'products.selling': 'Selling',
  'products.errorLoad': 'Could not load products',

  // New purchase
  'purchase.title': 'New purchase',
  'purchase.supplier': 'Supplier',
  'purchase.selectSupplier': 'Select supplier',
  'purchase.type': 'Type',
  'purchase.purchaseOrder': 'Purchase Order',
  'purchase.deliveredPurchase': 'Delivered Purchase',
  'purchase.poHint': 'A Purchase Order adds NO stock until it is marked Delivered.',
  'purchase.deliveredHint': 'A Delivered Purchase adds stock immediately.',
  'purchase.items': 'Items',
  'purchase.product': 'Product',
  'purchase.selectProduct': 'Select product',
  'purchase.qty': 'Qty',
  'purchase.cost': 'Cost / unit',
  'purchase.addItem': 'Add item',
  'purchase.removeItem': 'Remove',
  'purchase.notes': 'Notes',
  'purchase.notesPlaceholder': 'Extra details (optional)',
  'purchase.date': 'Date',
  'purchase.total': 'Total',
  'purchase.create': 'Save purchase',
  'purchase.creating': 'Saving…',
  'purchase.selectSupplierFirst': 'Select a supplier first',
  'purchase.addAtLeastOne': 'Add at least one item',
  'purchase.invalidItem': 'Each item needs a product, quantity and cost',
  'purchase.errorLoad': 'Could not load data',

  // Profile
  'profile.title': 'Profile',
  'profile.shopInfo': 'Shop information',
  'profile.shopName': 'Shop name',
  'profile.shopAddress': 'Shop address',
  'profile.phone': 'Phone',
  'profile.userName': 'Name',
  'profile.language': 'Language',
  'profile.english': 'English',
  'profile.urdu': 'اردو',
  'profile.theme': 'Theme',
  'profile.light': 'Light',
  'profile.dark': 'Dark',
  'profile.feedback': 'Send feedback',
  'profile.feedbackHint': 'Report a bug or suggest an improvement',
  'profile.logout': 'Logout',
  'profile.adminPanel': 'Admin panel',
  'profile.adminHint': 'Registered accounts & user feedback',

  // Feedback
  'feedback.title': 'Feedback',
  'feedback.category': 'Category',
  'feedback.bug': 'Bug',
  'feedback.suggestion': 'Suggestion',
  'feedback.other': 'Other',
  'feedback.message': 'Message',
  'feedback.messagePlaceholder': 'Describe the issue or your suggestion…',
  'feedback.submit': 'Submit',
  'feedback.submitting': 'Submitting…',
  'feedback.messageRequired': 'Please write a message',
  'feedback.thankYou': 'Thank you!',
  'feedback.thankYouHint': 'Your feedback has been received. We will review it soon.',
  'feedback.back': 'Back to profile',

  // Admin
  'admin.title': 'Admin panel',
  'admin.accessDenied': 'Access denied',
  'admin.accessDeniedHint': 'This page is for admins only.',
  'admin.accounts': 'Registered accounts',
  'admin.userFeedback': 'User feedback',
  'admin.noAccounts': 'No accounts yet',
  'admin.noFeedback': 'No feedback yet',
  'admin.createdOn': 'Joined',
  'admin.errorLoad': 'Could not load data',
};

export default en;
